import Head from "next/head"

function HeadPart() {
  return (
    <Head>
      <title>TODO App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default HeadPart
